version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - './.docker-data/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      TERM: '$TERM'
    ports:
      - '3306:3306'
  web:
    build:
      context: ./.docker-config/
      dockerfile: ./Dockerfile
      args:
        www_data_uid: "1000"
        www_data_gid: "1000"
    volumes:
      - '.:/app'
      - './.docker-config/vhost.conf:/etc/apache2/sites-available/000-default.conf'
      - './.docker-config/php.ini:/etc/php/php.ini'
    environment:
      PHP_VERSION: '7.4'
      COMPOSER_ALLOW_XDEBUG: '1
      TERM: '$TERM'
    ports:
      - '80:80'
      - '443:443'
